# Generated by Django 5.2.8 on 2025-11-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.CharField(default='no_images.img', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='productDesc',
            field=models.CharField(default='mặc định', max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='productName',
            field=models.CharField(default='mặc định', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
