# Generated by Django 5.2.8 on 2025-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_item_created_remove_item_name_item_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='manufacturerID',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='typeID',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='wareHouseID',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.CharField(default='no_images.img', max_length=2000),
        ),
    ]
